from PyQt5 import QtCore, QtWidgets, QtGui, QtMultimedia
from extra.other.custom_widgets import *
import json
import os


def setup(self, Form):
    try:
        with open('extra/json/data.json', 'r', encoding='utf-8') as f:
            self.json_data = json.load(f)
        with open('extra/backup/data.json', 'w', encoding='utf-8') as f:
            json.dump(self.json_data, f, ensure_ascii=False, indent=4)
        self.corrupted_data = False
    # If data has been corrupted
    except:
        # Load backup
        with open('extra/backup/data.json', 'r', encoding='utf-8') as f:
            self.json_data = json.load(f)
        with open('extra/json/data.json', 'w', encoding='utf-8') as f:
            json.dump(self.json_data, f, ensure_ascii=False, indent=4)
        self.corrupted_data = True

    with open('extra/json/config.json', 'r') as f:
        self.config = json.load(f)
    with open('extra/json/lang.json', 'r', encoding='utf-8') as f:
        self.lang_data = json.load(f)
    with open('extra/json/style.json', 'r', encoding='utf-8') as f:
        self.styles = json.load(f)
    Form.setObjectName("Form")
    Form.setEnabled(True)
    Form.resize(1920, 900)
    self.setWindowIcon(QtGui.QIcon('extra/imgs/music-notes.png'))
    self.theme = self.config['theme']
    self.full_discord_activities = self.config['full_discord_activities']
    self.stylesheets = self.styles['stylesheets'][self.theme]
    self.tracks_area_stylesheets = self.styles['tracks_area_stylesheets'][self.theme]
    self.rate_layout_stylesheets = self.styles['rate_stylesheets'][self.theme]
    Form.setStyleSheet(self.stylesheets)
    self.gridLayout_2 = QtWidgets.QGridLayout(Form)
    self.gridLayout_2.setObjectName("gridLayout_2")
    self.verticalLayout_9 = QtWidgets.QVBoxLayout()
    self.verticalLayout_9.setObjectName("verticalLayout_9")
    self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4.setObjectName("horizontalLayout_4")
    self.verticalLayout_4 = QtWidgets.QVBoxLayout()
    self.verticalLayout_4.setObjectName("verticalLayout_4")
    self.sidebar = QtWidgets.QListWidget(Form)
    self.sidebar.setWordWrap(True)
    self.sidebar.setMaximumSize(QtCore.QSize(171, 16777215))
    self.sidebar.setSizeIncrement(QtCore.QSize(50, 50))
    font = QtGui.QFont()
    font.setFamily("Microsoft JhengHei")
    font.setPointSize(10)
    font.setBold(True)
    font.setWeight(75)
    self.sidebar.setFont(font)
    self.sidebar.viewport().setProperty(
        "cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.sidebar.setStyleSheet("")
    self.sidebar.setObjectName("sidebar")
    self.verticalLayout_4.addWidget(self.sidebar)
    self.playlists = QtWidgets.QListWidget(Form)
    self.playlists.setWordWrap(True)
    self.playlists.setMaximumSize(QtCore.QSize(171, 16777215))
    self.playlists.setSizeIncrement(QtCore.QSize(50, 50))
    font = QtGui.QFont()
    font.setFamily("Microsoft JhengHei")
    font.setPointSize(10)
    font.setBold(True)
    font.setWeight(75)
    self.playlists.setFont(font)
    self.playlists.setStyleSheet("")
    self.playlists.setObjectName("playlists")
    self.verticalLayout_4.addWidget(self.playlists)
    self.delete_playlist_bttn = QtWidgets.QPushButton(Form)
    self.delete_playlist_bttn.setObjectName("delete_playlist_bttn")
    self.verticalLayout_4.addWidget(self.delete_playlist_bttn)
    self.verticalLayout_4.setStretch(0, 2)
    self.verticalLayout_4.setStretch(1, 5)
    self.horizontalLayout_4.addLayout(self.verticalLayout_4)
    self.verticalLayout_6 = QtWidgets.QVBoxLayout()
    self.verticalLayout_6.setObjectName("verticalLayout_6")
    self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_13.setObjectName("horizontalLayout_13")
    self.find_track_input = QtWidgets.QLineEdit(Form)
    self.find_track_input.setObjectName("find_track_input")
    self.horizontalLayout_13.addWidget(self.find_track_input)
    self.find_track_bttn = QtWidgets.QPushButton(Form)
    self.find_track_bttn.setObjectName("find_track_bttn")
    self.select_tracks_file_bttn = QtWidgets.QPushButton(Form)
    self.select_tracks_file_bttn.setObjectName("select_tracks_file_bttn")
    self.download_playlist_bttn = QtWidgets.QPushButton(Form)
    self.download_playlist_bttn.setObjectName("download_playlist_bttn")
    self.download_with_url_bttn = QtWidgets.QPushButton(Form)
    self.download_with_url_bttn.setObjectName("download_with_url_bttn")
    self.horizontalLayout_13.addWidget(self.find_track_bttn)
    self.horizontalLayout_13.addWidget(self.select_tracks_file_bttn)
    self.horizontalLayout_13.addWidget(self.download_playlist_bttn)
    self.horizontalLayout_13.addWidget(self.download_with_url_bttn)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_13.addItem(spacerItem)
    self.horizontalLayout_13.setStretch(0, 2)
    self.horizontalLayout_13.setStretch(1, 1)
    self.horizontalLayout_13.setStretch(2, 1)
    self.horizontalLayout_13.setStretch(3, 1)
    self.horizontalLayout_13.setStretch(4, 1)
    self.verticalLayout_6.addLayout(self.horizontalLayout_13)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.verticalLayout_7 = QtWidgets.QVBoxLayout()
    self.verticalLayout_7.setObjectName("verticalLayout_7")
    self.tracks_area = ThumbListWidget(self)
    self.tracks_area.setWordWrap(True)
    self.tracks_area.setObjectName("tracks_area")
    self.tracks_area.setStyleSheet("font: 20px; ")
    self.tracks_area.setStyleSheet(self.tracks_area_stylesheets)
    self.tracks_area.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
    self.tracks_area.setSelectionMode(3)
    self.rate_layout = QtWidgets.QVBoxLayout()
    self.track_name_rate_layout = QtWidgets.QHBoxLayout()
    self.const_rate_track_lbl = QtWidgets.QLabel('Назва трека: ')
    self.rate_track_name_lbl = QtWidgets.QLabel()
    self.rate_track_name_lbl.setObjectName("rate_track_name_lbl")
    self.track_name_rate_layout.addWidget(self.const_rate_track_lbl)
    self.track_name_rate_layout.addWidget(self.rate_track_name_lbl)
    self.track_name_rate_layout.setSpacing(25)
    self.track_name_rate_layout.setStretch(0, 1)
    self.track_name_rate_layout.setStretch(1, 4)
    self.const_rate_track_lbl.setStyleSheet(self.rate_layout_stylesheets)
    self.rate_track_name_lbl.setStyleSheet(self.rate_layout_stylesheets)
    self.rhymes_result_pattern = {'rhymes': 1, 'structure': 1, 'realization': 1, 'rizz': 1, 'vibe': 1, 'hype': 1}
    self.rhymes_rate = RateElement(self, 'Рими та образи', 'rhymes', 10, 'int')
    self.structure_rate = RateElement(self, 'Структура та ритміка', 'structure', 10, 'int')
    self.realization_rate = RateElement(self, 'Реалізація стилю', 'realization', 10, 'int')
    self.rizz_rate = RateElement(self, 'Індивідуальність та харизма', 'rizz', 10, 'int')
    self.vibe_rate = RateElement(self, 'Атмосфера та вайб', 'vibe', 5, 'percent')
    self.hype_rate = RateElement(self, 'Трендовість', 'hype', 5, 'percent')
    self.rate_elems = [self.rhymes_rate, self.structure_rate, self.realization_rate, self.rizz_rate, self.vibe_rate, self.hype_rate]
    self.rate_layout.addLayout(self.track_name_rate_layout)
    for i in self.rate_elems:
        i.setStyleSheet(self.rate_layout_stylesheets)
        self.rate_layout.addWidget(i)
    self.rate_result_lbl = QtWidgets.QLabel('1 + 1 + 1 + 1 + 10% + 10% = 1 pts')
    self.rate_result_lbl.setStyleSheet(self.rate_layout_stylesheets)
    self.rate_result_lbl.setAlignment(QtCore.Qt.AlignCenter)
    self.rate_result_bttn = QtWidgets.QPushButton()
    self.rate_result_bttn.setText('Оцінити')
    self.rate_result_bttn.setStyleSheet(self.rate_layout_stylesheets)
    self.rate_layout.addWidget(self.rate_result_lbl)
    self.rate_layout.addWidget(self.rate_result_bttn)
    self.another_elems = [self.const_rate_track_lbl, self.rate_track_name_lbl, self.rate_result_lbl, self.rate_result_bttn]
    for i in self.another_elems:
        self.rate_elems.append(i)
    self.verticalLayout_7.addLayout(self.rate_layout)

    self.verticalLayout_7.addWidget(self.tracks_area)
    self.track_area_action_bttn = QtWidgets.QPushButton(Form)
    self.track_area_action_bttn.setEnabled(True)
    self.track_area_action_bttn.setObjectName("track_area_action_bttn")
    self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_14.setObjectName("horizontalLayout_14")
    self.download_online_data_bttn = QtWidgets.QPushButton(Form)
    self.download_online_data_bttn.setEnabled(True)
    self.download_online_data_bttn.setObjectName(
        "download_online_data_bttn")
    self.horizontalLayout_14.addWidget(self.track_area_action_bttn)
    self.horizontalLayout_14.addWidget(self.download_online_data_bttn)
    self.verticalLayout_7.addLayout(self.horizontalLayout_14)
    self.horizontalLayout.addLayout(self.verticalLayout_7)
    self.gridLayout = QtWidgets.QGridLayout()
    self.gridLayout.setObjectName("gridLayout")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.recomendations_layout = QtWidgets.QHBoxLayout()
    self.rec_list = []
    for i in range(4):
        t1 = MainPageCell(str(i), os.path.abspath('extra\\imgs\\default_pic.jpg'))
        self.recomendations_layout.addWidget(t1)
        self.rec_list.append(t1)
    self.popular_tracks_layout = QtWidgets.QHBoxLayout()
    self.popular_list = []
    for i in range(4):
        t1 = MainPageCell(str(i), os.path.abspath('extra\\imgs\\default_pic.jpg'))
        self.popular_tracks_layout.addWidget(t1)
        self.popular_list.append(t1)
    self.verticalLayout_5 = QtWidgets.QVBoxLayout()
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.stat_lbl = QtWidgets.QLabel(Form)
    font = QtGui.QFont()
    font.setPointSize(20)
    self.recomendation_lbl = QtWidgets.QLabel(Form)
    self.recomendation_lbl.setFont(font)
    self.recomendation_lbl.setAlignment(QtCore.Qt.AlignCenter)
    self.popular_lbl = QtWidgets.QLabel(Form)
    self.popular_lbl.setFont(font)
    self.popular_lbl.setAlignment(QtCore.Qt.AlignCenter)
    self.stat_lbl.setFont(font)
    self.stat_lbl.setAlignment(QtCore.Qt.AlignCenter)
    self.stat_lbl.setObjectName("stat_lbl")
    self.stat_list = QtWidgets.QListWidget(Form)
    self.stat_list.setObjectName("stat_list")
    self.stat_list.setStyleSheet("font: 35px;")
    self.verticalLayout_5.addWidget(self.recomendation_lbl)
    self.verticalLayout_5.addLayout(self.recomendations_layout)
    self.verticalLayout_5.addWidget(self.popular_lbl)
    self.verticalLayout_5.addLayout(self.popular_tracks_layout)
    self.verticalLayout_5.addWidget(self.stat_lbl)
    self.verticalLayout_5.addWidget(self.stat_list)
    self.verticalLayout.addLayout(self.verticalLayout_5)
    self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
    self.verticalLayout_11 = QtWidgets.QVBoxLayout()
    self.horizontalLayout.addLayout(self.gridLayout)
    self.verticalLayout_6.addLayout(self.horizontalLayout)
    self.horizontalLayout_4.addLayout(self.verticalLayout_6)
    self.queue_listwidget = QtWidgets.QListWidget(Form)
    self.queue_listwidget.setWordWrap(True)
    self.queue_listwidget.setObjectName("queue_listwidget")
    self.queue_lbl = QtWidgets.QLabel(Form)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.queue_lbl.setFont(font)
    self.queue_lbl.setAlignment(QtCore.Qt.AlignCenter)
    self.queue_lbl.setObjectName("queue_lbl")
    self.logs_lbl = QtWidgets.QLabel(Form)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.logs_lbl.setFont(font)
    self.logs_lbl.setAlignment(QtCore.Qt.AlignCenter)
    self.logs_listwidget = QtWidgets.QListWidget(Form)
    self.logs_listwidget.setObjectName("queue_listwidget")
    self.logs_listwidget.setWordWrap(True)
    self.queue_layout = QtWidgets.QVBoxLayout()
    self.queue_layout.addWidget(self.queue_lbl)
    self.queue_layout.addWidget(self.queue_listwidget)
    self.queue_layout.addWidget(self.logs_lbl)
    self.queue_layout.addWidget(self.logs_listwidget)
    self.queue_layout.setStretch(1, 3)
    self.horizontalLayout_4.addLayout(self.queue_layout)
    self.horizontalLayout_4.setStretch(0, 3)
    self.horizontalLayout_4.setStretch(1, 28)
    self.horizontalLayout_4.setStretch(2, 3)
    self.verticalLayout_9.addLayout(self.horizontalLayout_4)
    spacerItem1 = QtWidgets.QSpacerItem(
        20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout_9.addItem(spacerItem1)
    self.verticalLayout_8 = QtWidgets.QVBoxLayout()
    self.verticalLayout_8.setObjectName("verticalLayout_8")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout()
    self.verticalLayout_2.setSpacing(8)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3.setSpacing(90)
    self.horizontalLayout_3.setObjectName("horizontalLayout_3")
    spacerItem2 = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_3.addItem(spacerItem2)
    self.settings_bttn = QtWidgets.QPushButton(Form)
    self.settings_bttn.setObjectName("settings_bttn")
    self.horizontalLayout_3.addWidget(self.settings_bttn)
    self.prev_bttn = QtWidgets.QPushButton(Form)
    self.prev_bttn.setObjectName("prev_bttn")
    self.horizontalLayout_3.addWidget(self.prev_bttn)
    self.play_bttn = QtWidgets.QPushButton(Form)
    self.play_bttn.setObjectName("play_bttn")
    self.horizontalLayout_3.addWidget(self.play_bttn)
    self.next_bttn = QtWidgets.QPushButton(Form)
    self.next_bttn.setObjectName("next_bttn")
    self.horizontalLayout_3.addWidget(self.next_bttn)
    self.repeat_bttn = QtWidgets.QPushButton(Form)
    self.repeat_bttn.setObjectName("repeat_bttn")
    self.horizontalLayout_3.addWidget(self.repeat_bttn)
    spacerItem3 = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_3.addItem(spacerItem3)
    self.horizontalLayout_3.setStretch(0, 13)
    self.horizontalLayout_3.setStretch(1, 3)
    self.horizontalLayout_3.setStretch(2, 12)
    self.horizontalLayout_3.setStretch(3, 8)
    self.horizontalLayout_3.setStretch(4, 12)
    self.horizontalLayout_3.setStretch(5, 3)
    self.horizontalLayout_3.setStretch(6, 13)
    self.verticalLayout_2.addLayout(self.horizontalLayout_3)
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setSpacing(5)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.track_name_lbl = QtWidgets.QLabel(Form)
    self.track_name_lbl.setWordWrap(True)
    self.track_name_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.track_name_lbl.setStyleSheet("color: white")
    self.track_name_lbl.setAlignment(
        QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
    self.track_name_lbl.setObjectName("track_name_lbl")
    self.horizontalLayout_2.addWidget(self.track_name_lbl)
    spacerItem4 = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_2.addItem(spacerItem4)
    self.current_track_time = QtWidgets.QLabel(Form)
    self.current_track_time.setLayoutDirection(QtCore.Qt.LeftToRight)
    self.current_track_time.setStyleSheet("color: white")
    self.current_track_time.setObjectName("current_track_time")
    self.horizontalLayout_2.addWidget(self.current_track_time)
    self.track_slider = QtWidgets.QSlider(Form)
    self.track_slider.setOrientation(QtCore.Qt.Horizontal)
    self.track_slider.setObjectName("track_slider")
    self.horizontalLayout_2.addWidget(self.track_slider)
    self.all_track_time = QtWidgets.QLabel(Form)
    self.all_track_time.setStyleSheet("color: white")
    self.all_track_time.setObjectName("all_track_time")
    self.horizontalLayout_2.addWidget(self.all_track_time)
    spacerItem5 = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_2.addItem(spacerItem5)
    self.verticalLayout_10 = QtWidgets.QVBoxLayout()
    self.verticalLayout_10.setObjectName("verticalLayout_10")
    self.volume_lbl = QtWidgets.QLabel(Form)
    font = QtGui.QFont()
    font.setPointSize(10)
    font.setBold(False)
    font.setWeight(50)
    self.volume_lbl.setFont(font)
    self.volume_lbl.setStyleSheet("color: white;")
    self.volume_lbl.setObjectName("volume_lbl")
    self.verticalLayout_10.addWidget(self.volume_lbl)
    self.volume_slider = QtWidgets.QSlider(Form)
    self.volume_slider.setSingleStep(self.config["volume_step"])
    self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
    self.volume_slider.setObjectName("volume_slider")
    self.volume_slider.setMinimum(0)
    self.volume_slider.setMaximum(100)
    self.verticalLayout_10.addWidget(self.volume_slider)
    self.horizontalLayout_2.addLayout(self.verticalLayout_10)
    self.horizontalLayout_2.setStretch(0, 4)
    self.horizontalLayout_2.setStretch(1, 1)
    self.horizontalLayout_2.setStretch(2, 2)
    self.horizontalLayout_2.setStretch(3, 30)
    self.horizontalLayout_2.setStretch(5, 5)
    self.verticalLayout_2.addLayout(self.horizontalLayout_2)
    self.verticalLayout_2.setStretch(0, 3)
    self.verticalLayout_2.setStretch(1, 3)
    self.verticalLayout_8.addLayout(self.verticalLayout_2)
    self.verticalLayout_9.addLayout(self.verticalLayout_8)
    self.verticalLayout_9.setStretch(0, 28)
    self.verticalLayout_9.setStretch(1, 1)
    self.verticalLayout_9.setStretch(2, 4)
    self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
    self.retranslateUi(Form)
    QtCore.QMetaObject.connectSlotsByName(Form)